# Site settings
title: Josep Anton Mir Tutusaus CV
description: Josep Anton Mir Tutusaus CV
favicon: assets/img/profile.png
#baseurl: https://jantonz.github.io/Resume
url: https://jantonz.github.io/Resume/
#rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Josep Anton Mir Tutusaus
  title: Environmental Engineer, Data Scientist, Python & R developer, Deep Learning Ninja
  address: Vilafranca del Penedès, Barcelona
  email: jantonz@gmail.com
#  link: http://ddbullfrog.com
  weibo:
  github: jantonz
  linkedin: josepantonmir
  twitter: Josep_Anton_Mir_Tutusaus # En realitat està canviat per researchgate
  gavatar: assets/img/profile.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  teachingHistory:
    - teaching1:
      started: 2005
      course: R
      organization: XXXXXX University
      location: Shenyang, China
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - teaching2:
      started: 2005
      course: Big Data
      organization: XXXXXX University
      location: Shenyang, China
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - teaching3:
      started: 2005
      course:
      organization: XXXXXX University
      location: Shenyang, China
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Catalan
      proficiency: Native
    - language2:
      name: English
      proficiency: Proficient
    - language3:
      name: Spanish
      proficiency: Native
    - language4:
      name: French
      proficiency: Proficient
    - language4:
      name: German
      proficiency: Elementary
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: R
      percentage: 100%
    - skill3:
      name: Octave/Matlab
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
